sudo: required 
services: 
  - docker 

before_install: 
  - docker build -t docker_image -f Dockerfile.dev .  # docker_image is the name of the image. We cannot select the image using 'docker ps'

script: 
  - docker run -e CI=true docker_image npm run test 




