version: '3'
services: 
  web: 
    build: 
      context: .  # This specifies where we want the folders to be pulled from ie the current wordking directory '.' 
      dockerfile: Dockerfile.dev 
    ports: 
      - "3000:3000"
    volumes: 
      - /home/node/app/node_modules # Do not map this folder
      - .:/home/node/app            # Map '.', the current working directory into the /app folder inside the container 

  tests: 
    build: 
      context: .  
      dockerfile: Dockerfile.dev 
    volumes: 
      - /home/node/app/node_modules 
      - .:/home/node/app 
    command: ["npm", "run", "test"]




